### ISSUE TITLE
Restore accidental deletion of collection 

### ISSUE THREAD

**Issue by apnerve** [chinchang/ask-me-anything#1]
Is it possible to restore an accidental deletion of firestore collection(Free plan)

PS: Sorry, didn't want to turn this AMA into Stackoverflow but I'm helpless at the moment

**Comment by chinchang** [comment]
I won't say 100%, but pretty sure that won't be possible :(
If you are a big Firebase customer and you have some contact in Google, maybe, just maybe they can help to get data back for you from their backups (if they exist)

That said, you should regularly [export your data](https://firebase.google.com/docs/firestore/manage-data/export-import) to avoid this in future.
